# Numpy 배열 사용하기

** INTRO **
- 변수에 여러 가지 값을 넣어서 사용하기
- 변수에 여러 가지 값을 넣는 방법: 리스
트(list) / 배열(array)
    1. 리스트: I feel you should use a list just because it is supported **in the syntax** and **is used more widely in the other libraries**, etc.
    2. 배열: You should use arrays if you know that everything in the "list" will **be of the same type** and you want to store the data **more compactly**
- 파이썬(python)에서는 배열을 제공해주고 있지 않음.
- 다른 라이브러리(library)를 임포트(import) 할 필요가 있음

**NumPy**
1. 수치해석용 Python 라이브러리
2. ndarray 다차원 배열 자료 클래스 제공
3. ~~BLAS/LAPACK 기반~~
4. ~~CPython에서만 사용 가능~~
5. ~~내부 반복문 사용으로 빠른 배열 연산 가능~~
6. 배열 인덱싱(array indexing)을 사용한 질의(Query) 기능

In [4]:
# numpy 패키지 임포트하기
import numpy as np

In [20]:
# 1차원 배열 만들기
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a_list = [1,2,3,4,'5','6','7']
a_list

[1, 2, 3, 4, '5', '6', '7']

In [24]:
type(a_list)

list

In [23]:
a_array = np.array([1,2,3,4,'5','6','7'])
a_array

array(['1', '2', '3', '4', '5', '6', '7'], 
      dtype='<U11')

In [25]:
type(a_array)

numpy.ndarray

** *함수 설명 **
- numpy.array([numpy.array 링크보기](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html)): create an array

In [17]:
type(a)

numpy.ndarray

In [2]:
a = [0,1,2,3,4,5,6,7,8]
b = []
for ai in a:
    b.append(ai * 2)
b

[0, 2, 4, 6, 8, 10, 12, 14, 16]

In [6]:
# 벡터화 연산
x = np.array(a)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
# 배열에 2를 곱했을 경우
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [14]:
# 리스트에 2를 곱했을 경우
y = [0,1,2,3,4,5,6,7,8]
y * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8]

In [24]:
# 벡터화 연산은 모든 종류의 수학 연산에 적용 가능
a = np.array([1,2,3])
b = np.array([10,20,30])
2 * a + b

array([12, 24, 36])

In [30]:
# 배열에 지수화하기
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692])

In [29]:
# 배열에 로그화하기
np.log(b)

array([ 2.30258509,  2.99573227,  3.40119738])

## 2차원 배열 만들기

- ndarray는 N-dimensional Array의 약자
- 2차원 배열은 행렬(matrix)이라고도 함

In [34]:
# 2x3 배열(array)
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
len(c)

2

In [40]:
len(c[0])

3

In [43]:
practice_01 = np.array([[10,20,30,40],[50,60,70,80]])
practice_01

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차월 배열 만들기

In [45]:
# 2x3x4 배열 만들기
three_dimension_array = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
three_dimension_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [48]:
len(three_dimension_array)

2

In [49]:
len(three_dimension_array[0])

3

In [50]:
len(three_dimension_array[0][0])

4

## 배열의 차원과 크기 알아내기/ 인덱싱 / 슬라이싱

배열의 차원 및 크기는 ndim과 shape로 알아낼 수 있음

In [55]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
c.ndim

2

In [57]:
c.shape

(2, 3)

In [61]:
# 첫번째 행 전체
c[0,:]

array([0, 1, 2])

In [65]:
# 두번째 열 전체
c[:,1]

array([1, 4])

In [69]:
# 두 번째 행의 두 번째 열부터 끝까지
c[1,1:]

array([4, 5])

In [72]:
practice_02 = np.array([[0,1,2,3,4,],[5,6,7,8,9],[10,11,12,13,14]])
practice_02

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
# 배열 [7,12] 슬라이싱 해보기
practice_02[1:,2]

array([ 7, 12])

In [76]:
# 배열 [[3,4,],[8,9]] 슬라이싱 해보기
practice_02[:2,3:]

array([[3, 4],
       [8, 9]])

## Fancy Indexing (배열 인덱싱 방법)

- 배열 인덱싱에서 [](대괄호, bracket)안의 인덱스 정보로 숫자나 슬라이스가 아닌 ndarray 배열을 받을 수 있음
- ndarray 배열은 크게 1)**불리안(Boolean) 배열** 방식과 2)**정수 배열** 방식이 있음
- 1)불리안 배열은, True/False로 구성. 인덱스의 크기가 배열의 크기와 같아야 함
- 2)정수 배열은, 위치에 대한 정보로 구성. 인덱스의 크기가 배열의 크기와 달라도 됨

In [89]:
# Boolean Array: 불리안 배열을 통해 짝수 골라내기
boolean_array = np.array([0,1,2,3,4,5,6,7])
idx = np.array([True,False,True,False,True,False,True,False])
boolean_array[idx]

array([0, 2, 4, 6])

In [83]:
# 조건문 연산 사용하여 짝수 골라내기
boolean_array[boolean_array % 2 == 0]

array([0, 2, 4, 6])

In [85]:
# Integer Array: 정수 배열을 통해 짝수 골라내기
integer_array = np.array([0,1,2,3,4,5,6,7])
idx02 = np.array([0,2,4,6])
integer_array[idx02]

array([0, 2, 4, 6])

In [87]:
idx03 = np.array([0,0,0,2,2,4,6])
integer_array[idx03]

array([0, 0, 0, 2, 2, 4, 6])