# NumPy 배열의 연산

In [12]:
import numpy as np

In [13]:
x = np.arange(1, 1001)
y = np.arange(1001, 2001)

In [14]:
x[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
y[:10]

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [39]:
%%time
z = np.zeros_like(x)
for i in range(1000):
    z[i] = x[i] + y[i]

Wall time: 1 ms


** Magic Function **
- [자세한 설명 바로가기: Domino 블로그](https://blog.dominodatalab.com/lesser-known-ways-of-using-notebooks/)
- [Domino: Data Science Solution](https://www.dominodatalab.com/)
- [자세한 설명 바로가기: Jupyter Notebook](https://ipython.readthedocs.io/en/stable/interactive/tutorial.html#magics-explained)
- you can run different types of code in different cells. With "magics", it is possible to use different languages
- %timeit will time whatever you evaluate multiple times and give you the best, and the average times

In [11]:
z[:10]

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020])

In [38]:
%%time
z = x + y

Wall time: 0 ns


In [41]:
z[:10]

array([1002, 1004, 1006, 1008, 1010, 1012, 1014, 1016, 1018, 1020])

In [44]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a == b

array([False, False, False, False], dtype=bool)

In [45]:
a >= b

array([False, False, False, False], dtype=bool)

## 스칼라와 벡터(행렬)의 곱셈

In [49]:
x = np.arange(10)
x * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [52]:
y = np.arange(12).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
y * 100

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

##  브로드캐스팅

In [63]:
broad_test_01 = np.arange(5)
broad_test_01

array([0, 1, 2, 3, 4])

In [60]:
test1 = np.ones(broad_test_01)
test2 = np.ones_like(broad_test_01)

In [65]:
test1

array([], shape=(0, 1, 2, 3, 4), dtype=float64)

In [62]:
test2

array([1, 1, 1, 1, 1])

In [67]:
broad_test_01 + test2

array([1, 2, 3, 4, 5])

In [68]:
broad_test_01 + 1

array([1, 2, 3, 4, 5])

In [75]:
%%html
<img src='https://datascienceschool.net/upfiles/dbd3775c3b914d4e8c6bbbb342246b6a.png'>Broadcasting Example</img>

In [81]:
broad_test_02 = np.tile(np.arange(0,40,10),(3,1))
broad_test_02

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

** numpy.tile **
- Construct an array by repeating A the number of times given by reps.
- [See More](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html)

In [85]:
module_01 = broad_test_02.T
module_01

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [105]:
module_02 = np.tile(np.arange(0,3,1),(4,1))
module_02

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [111]:
module_03 = np.arange(0,3,1)
module_03

array([0, 1, 2])

In [110]:
module_04 = np.arange(0,40,10).reshape(4,1)
module_04

array([[ 0],
       [10],
       [20],
       [30]])

In [106]:
module_01 + module_02

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [107]:
module_01 + module_03

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [112]:
module_04 + module_03

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

## 차원 축소 연산

- 최대/최소: min, max, argmin, argmax
- 통계: sum, mean, median, std, var
- 불리언: all, any

In [115]:
reduction_test = np.array([1,2,3,4])
reduction_test

array([1, 2, 3, 4])

In [116]:
np.sum(reduction_test)

10

In [117]:
reduction_test.sum()

10

In [119]:
reduction_test.mean()

2.5

In [121]:
reduction_test_twodim = np.array([[1,2],[3,4]])
reduction_test_twodim

array([[1, 2],
       [3, 4]])

In [127]:
# 열 합계
reduction_test_twodim.sum(axis=0)

array([4, 6])

In [128]:
# 행 합계
reduction_test_twodim.sum(axis=1)

array([3, 7])

In [132]:
practice_01 = np.arange(1,31,1).reshape(5,6)
practice_01

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [137]:
practice_01.max()

30

In [138]:
practice_01.sum(axis=1)

array([ 21,  57,  93, 129, 165])

In [142]:
practice_01.mean(axis=0, dtype=np.int)

array([13, 14, 15, 16, 17, 18])

In [143]:
practice_01.mean(axis=0, dtype="i8")

array([13, 14, 15, 16, 17, 18], dtype=int64)

** numpy.ndarray **
- [See more attributes and methods](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html)

## 정렬

In [150]:
sort_test = np.array([[4,3,5],[1,2,1]])
sort_test

array([[4, 3, 5],
       [1, 2, 1]])

In [152]:
sort_test.sort()
sort_test

array([[3, 4, 5],
       [1, 1, 2]])

In [154]:
arg_sort_test = np.array([4,3,1,2])
arg_sort_test

array([4, 3, 1, 2])

In [158]:
# 왜 결과 값이 이러는지?
sort_index = np.argsort(arg_sort_test)
sort_index

array([2, 3, 1, 0], dtype=int64)

In [157]:
arg_sort_test[sort_index]

array([1, 2, 3, 4])

In [201]:
practice_02 = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
practice_02

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [203]:
sort_01 = np.argsort(practice_02, axis=1)
practice_02.sort(axis=1)
practice_02
# practice_02[sort_01]

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])