#  Numpy 배열의 생성과 변형

- Numpy의 ndarray 클래스틑 모든 데이터가 동일한 자료형(data type)이어야 함. 파이썬에서 기본적으로 제공하는 자료형보다 훨씬 세분화 되어 있음. 
- [Python Data Type 바로가기](https://www.programiz.com/python-programming/variables-datatypes)

In [12]:
import numpy as np

** *numpy.zeros 설명**
- Return a new array of given shape and type, filled with zeros.
- [설명바로가기](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)

In [3]:
a= np.zeros(5)
a

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
b = np.zeros((5), dtype="S")
b

array([b'', b'', b'', b'', b''], 
      dtype='|S1')

In [30]:
c = np.ones((5,2), dtype="i8")
c

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

**리스트(list)와 튜플(tuple)**
1. 리스트는 '[' 와 ']'를 사용하는 반면 튜플은 '('와 ')'를 사용한다. 
2. 리스트는 리스트 내의 원소를 변경할 수 있지만 튜플은 변경할 수 없다. 
3. 튜플은 리스트보다 속도가 빠르다는 장점이 있습니다. 따라서 한번 데이터를 저장해둔 후 추가하거나 삭제할 필요가 없는 경우라면 되도록 리스트보다는 튜플을 사용하는 것이 좋습니다

In [32]:
#range()
e = range(10)
f = np.ones_like(e, dtype="f")
f

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [33]:
# numpy.arange(a,b,c) 시작, 끝, 갯수
f = np.ones_like(np.arange(10), dtype="f")
f

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.], dtype=float32)

In [50]:
# Random Sampling
np.random.rand(5)

array([ 0.30145286,  0.04736134,  0.23945524,  0.10652438,  0.0534189 ])

In [53]:
# Random Sampling: Return random integers from low (inclusive) to high (exclusive).
np.random.randint(1,10,5,dtype='i')

array([8, 7, 4, 9, 7])

[랜덤 샘플링 더 알아보기](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

## 전치 연산 (transpose)

행과 열을 바꿔주는 작업. 배열의 T 속성으로 작업 가능. 메서드가 아닌 속성임

In [88]:
transpose_test = np.array([[np.arange(2,11,2)],[np.arange(0,10,2)]])
transpose_test

array([[[ 2,  4,  6,  8, 10]],

       [[ 0,  2,  4,  6,  8]]])

In [91]:
# T속성을 이용하여 행열바꿔주기
transpose_test.T

array([[[ 2,  0]],

       [[ 4,  2]],

       [[ 6,  4]],

       [[ 8,  6]],

       [[10,  8]]])

##  배열의 크기 변형

In [104]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [105]:
a.shape

(12,)

In [115]:
b = a.reshape(2,2,-1)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [116]:
b.ndim
b.shape

(2, 2, 3)

In [117]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 배열 연결

[바로가기](https://datascienceschool.net/view-notebook/17608f897087478bbeac096438c716f6/)